#!/bin/bash
#postrm (script executed after uninstalling the package)
#set -e

if [ -f /bin/xwinwrap ]; then
    rm /bin/xwinwrap
fi

if [ -f /bin/gwinwrap ]; then
    rm /bin/gwinwrap
fi

if [ -f /usr/share/applications/gwinwrap.desktop ]; then
    rm /usr/share/applications/gwinwrap.desktop
fi

if [ -f /opt/gwinwrap.zip ]; then
    rm /opt/gwinwrap.zip
fi

if [ -d /usr/share/gwinwrap ]; then
    rm -rf /usr/share/gwinwrap
fi
